using System.Linq;
//Erida start
using Content.Client._Sunrise.UserInterface.Controls;
using Content.Client.Guidebook.Controls;
using Content.Shared._Sunrise.MarkingEffects;
//Erida end
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class LayerMarkingItem : BoxContainer, ISearchableControl
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private readonly SpriteSystem _sprite;

    private readonly MarkingsViewModel _markingsModel;
    private readonly MarkingPrototype _markingPrototype;
    private readonly ProtoId<OrganCategoryPrototype> _organ;
    private readonly HumanoidVisualLayers _layer;
    private readonly bool _shareEffectAcrossSprites; //Erida edit
    private bool _interactive;

    private List<MarkingEffectSelectorSliders>? _effectSliders; //Erida edit
    private bool _updatingControls;

    public event Action<GUIBoundKeyEventArgs, LayerMarkingItem>? Pressed;
    public event Action<GUIBoundKeyEventArgs, LayerMarkingItem>? Unpressed;
    public ProtoId<MarkingPrototype> MarkingId => _markingPrototype.ID;

    public LayerMarkingItem(MarkingsViewModel model, ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer, MarkingPrototype prototype, bool interactive)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();

        _markingsModel = model;
        _markingPrototype = prototype;
        _organ = organ;
        _layer = layer;
        _shareEffectAcrossSprites = _layer == HumanoidVisualLayers.Tail; //Erida edit
        _interactive = interactive;

        UpdateData();
        UpdateSelection();

        SelectButton.OnPressed += SelectButtonPressed;
        ColorsButton.OnPressed += ColorsButtonPressed;

        OnKeyBindDown += OnPressed;
        OnKeyBindUp += OnUnpressed;

        if (!interactive)
        {
            SelectButton.MouseFilter = Control.MouseFilterMode.Ignore;
        }
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel.MarkingsReset += UpdateSelection;
        _markingsModel.MarkingsChanged += MarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel.MarkingsReset -= UpdateSelection;
        _markingsModel.MarkingsChanged -= MarkingsChanged;
    }

    private void MarkingsChanged(ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer)
    {
        if (_organ != organ ||  _layer != layer)
            return;

        UpdateSelection();
    }

    private void UpdateData()
    {
        MarkingTexture.Textures = _markingPrototype.Sprites.Select(layer => _sprite.Frame0(layer)).ToList();
        SelectButton.Text = Loc.GetString($"marking-{_markingPrototype.ID}");
    }

    private void UpdateSelection()
    {
        var selected = _markingsModel.IsMarkingSelected(_organ, _layer, _markingPrototype.ID);
        SelectButton.Pressed = selected && _interactive;
        ColorsButton.Visible = selected && _interactive && _markingsModel.IsMarkingColorCustomizable(_organ, _layer, _markingPrototype.ID);

        if (!selected || !_interactive)
        {
            ColorsButton.Pressed = false;
            ColorsContainer.Visible = false;
        }

        //Erida start
        if (_markingsModel.GetMarking(_organ, _layer, _markingPrototype.ID) is { } marking &&
            _effectSliders is { } sliders)
        {
            _updatingControls = true;
            for (var i = 0; i < GetEffectSelectorCount() && i < sliders.Count; i++)
            {
                var effect = GetLayerEffect(marking, GetEffectColorIndex(i));
                sliders[i].CurrentType = effect.Type;
            }
            _updatingControls = false;
        }
        //Erida end
    }

    private void SelectButtonPressed(BaseButton.ButtonEventArgs args)
    {
        if (!_interactive)
        {
            SelectButton.Pressed = false;
            return;
        }

        if (_markingsModel.IsMarkingSelected(_organ, _layer, _markingPrototype.ID))
        {
            if (!_markingsModel.TryDeselectMarking(_organ, _layer, _markingPrototype.ID))
            {
                SelectButton.Pressed = true;
            }
        }
        else
        {
            if (!_markingsModel.TrySelectMarking(_organ, _layer, _markingPrototype.ID))
            {
                SelectButton.Pressed = false;
            }
        }
    }

    //Erida start
    private void ColorsButtonPressed(BaseButton.ButtonEventArgs args)
    {
        ColorsContainer.Visible = ColorsButton.Pressed;

        if (_effectSliders is not null)
            return;

        if (_markingsModel.GetMarking(_organ, _layer, _markingPrototype.ID) is not { } marking)
            return;

        _effectSliders = new();

        for (var i = 0; i < GetEffectSelectorCount(); i++)
        {
            var container = new BoxContainer()
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            ColorsContainer.AddChild(container);

            if (!_shareEffectAcrossSprites && TryGetSpriteLayerLabel(_markingPrototype, i, out var label))
                container.AddChild(new Label { Text = label });

            var colorIndex = GetEffectColorIndex(i);
            var effectSelector = new MarkingEffectSelectorSliders(GetLayerEffect(marking, colorIndex).Clone())
            {
                HorizontalExpand = true,
            };

            effectSelector.OnColorChanged += effect =>
            {
                if (_updatingControls)
                    return;

                if (!_shareEffectAcrossSprites)
                {
                    _markingsModel.TrySetMarkingEffect(_organ, _layer, _markingPrototype.ID, colorIndex, effect.Clone());
                    return;
                }

                for (var j = 0; j < _markingPrototype.Sprites.Count; j++)
                {
                    _markingsModel.TrySetMarkingEffect(_organ, _layer, _markingPrototype.ID, j, effect.Clone());
                }
            };

            _effectSliders.Add(effectSelector);
            container.AddChild(effectSelector);
        }
    }

    private int GetEffectSelectorCount()
    {
        return _shareEffectAcrossSprites
            ? 1
            : _markingPrototype.Sprites.Count;
    }

    private int GetEffectColorIndex(int selectorIndex)
    {
        return _shareEffectAcrossSprites
            ? 0
            : selectorIndex;
    }

    private static MarkingEffect GetLayerEffect(Marking marking, int colorIndex)
    {
        if (colorIndex < marking.MarkingEffects.Count)
            return marking.MarkingEffects[colorIndex];

        var color = colorIndex < marking.MarkingColors.Count
            ? marking.MarkingColors[colorIndex]
            : Color.White;

        return new ColorMarkingEffect(color);
    }

    private static bool TryGetSpriteLayerLabel(MarkingPrototype marking, int colorIndex, out string label)
    {
        var locKey = marking.Sprites[colorIndex] switch
        {
            SpriteSpecifier.Rsi rsi => $"marking-{marking.ID}-{rsi.RsiState}",
            SpriteSpecifier.Texture texture => $"marking-{marking.ID}-{texture.TexturePath.Filename}",
            _ => throw new InvalidOperationException("SpriteSpecifier not of known type"),
        };

        if (Loc.TryGetString(locKey, out label!))
            return true;

        label = string.Empty;
        return false;
    }

    //Erida end

    public bool CheckMatchesSearch(string query)
    {
        return Loc.GetString($"marking-{_markingPrototype.ID}").Contains(query, StringComparison.OrdinalIgnoreCase);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    private void OnPressed(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        Pressed?.Invoke(args, this);
    }

    private void OnUnpressed(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        Unpressed?.Invoke(args, this);
    }
}
