using System.Linq;
using Content.Client.Guidebook.Controls;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class LayerMarkingItem : BoxContainer, ISearchableControl
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private readonly SpriteSystem _sprite;

    private readonly MarkingsViewModel _markingsModel;
    private readonly MarkingPrototype _markingPrototype;
    private readonly ProtoId<OrganCategoryPrototype> _organ;
    private readonly HumanoidVisualLayers _layer;
    private bool _interactive;

    private List<ColorSelectorSliders>? _colorSliders;
    private List<OptionButton>? _gradientTypeButtons;
    private List<ColorSelectorSliders>? _gradientColorSliders;
    private List<Slider>? _gradientAngleSliders;
    private List<Slider>? _gradientOffsetSliders;
    private List<Slider>? _gradientSoftnessSliders;
    private List<BoxContainer>? _gradientColorContainers;
    private List<BoxContainer>? _gradientSettingsContainers;
    private bool _updatingControls;

    private static readonly MarkingGradientType[] GradientTypes =
    [
        MarkingGradientType.None,
        MarkingGradientType.Vertical,
        MarkingGradientType.Horizontal,
        MarkingGradientType.Diagonal,
        MarkingGradientType.ReverseDiagonal,
        MarkingGradientType.Radial,
    ];

    public event Action<GUIBoundKeyEventArgs, LayerMarkingItem>? Pressed;
    public event Action<GUIBoundKeyEventArgs, LayerMarkingItem>? Unpressed;
    public ProtoId<MarkingPrototype> MarkingId => _markingPrototype.ID;

    public LayerMarkingItem(MarkingsViewModel model, ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer, MarkingPrototype prototype, bool interactive)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();

        _markingsModel = model;
        _markingPrototype = prototype;
        _organ = organ;
        _layer = layer;
        _interactive = interactive;

        UpdateData();
        UpdateSelection();

        SelectButton.OnPressed += SelectButtonPressed;
        ColorsButton.OnPressed += ColorsButtonPressed;

        OnKeyBindDown += OnPressed;
        OnKeyBindUp += OnUnpressed;

        if (!interactive)
        {
            SelectButton.MouseFilter = Control.MouseFilterMode.Ignore;
        }
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel.MarkingsReset += UpdateSelection;
        _markingsModel.MarkingsChanged += MarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel.MarkingsReset -= UpdateSelection;
        _markingsModel.MarkingsChanged -= MarkingsChanged;
    }

    private void MarkingsChanged(ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer)
    {
        if (_organ != organ ||  _layer != layer)
            return;

        UpdateSelection();
    }

    private void UpdateData()
    {
        MarkingTexture.Textures = _markingPrototype.Sprites.Select(layer => _sprite.Frame0(layer)).ToList();
        SelectButton.Text = Loc.GetString($"marking-{_markingPrototype.ID}");
    }

    private void UpdateSelection()
    {
        var selected = _markingsModel.IsMarkingSelected(_organ, _layer, _markingPrototype.ID);
        SelectButton.Pressed = selected && _interactive;
        ColorsButton.Visible = selected && _interactive && _markingsModel.IsMarkingColorCustomizable(_organ, _layer, _markingPrototype.ID);

        if (!selected || !_interactive)
        {
            ColorsButton.Pressed = false;
            ColorsContainer.Visible = false;
        }

        if (_markingsModel.GetMarking(_organ, _layer, _markingPrototype.ID) is { } marking &&
            _colorSliders is { } sliders)
        {
            _updatingControls = true;
            for (var i = 0; i < _markingPrototype.Sprites.Count; i++)
            {
                sliders[i].Color = marking.MarkingColors[i];
                UpdateGradientControls(marking, i);
            }
            _updatingControls = false;
        }
    }

    private void SelectButtonPressed(BaseButton.ButtonEventArgs args)
    {
        if (!_interactive)
        {
            SelectButton.Pressed = false;
            return;
        }

        if (_markingsModel.IsMarkingSelected(_organ, _layer, _markingPrototype.ID))
        {
            if (!_markingsModel.TryDeselectMarking(_organ, _layer, _markingPrototype.ID))
            {
                SelectButton.Pressed = true;
            }
        }
        else
        {
            if (!_markingsModel.TrySelectMarking(_organ, _layer, _markingPrototype.ID))
            {
                SelectButton.Pressed = false;
            }
        }
    }

    private void ColorsButtonPressed(BaseButton.ButtonEventArgs args)
    {
        ColorsContainer.Visible = ColorsButton.Pressed;

        if (_colorSliders is not null)
            return;

        if (_markingsModel.GetMarking(_organ, _layer, _markingPrototype.ID) is not { } marking)
            return;

        _colorSliders = new();
        _gradientTypeButtons = new();
        _gradientColorSliders = new();
        _gradientAngleSliders = new();
        _gradientOffsetSliders = new();
        _gradientSoftnessSliders = new();
        _gradientColorContainers = new();
        _gradientSettingsContainers = new();

        for (var i = 0; i < _markingPrototype.Sprites.Count; i++)
        {
            var container = new BoxContainer()
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            ColorsContainer.AddChild(container);

            var selector = new ColorSelectorSliders();
            selector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;

            var label = _markingPrototype.Sprites[i] switch
            {
                SpriteSpecifier.Rsi rsi => Loc.GetString($"marking-{_markingPrototype.ID}-{rsi.RsiState}"),
                SpriteSpecifier.Texture texture => Loc.GetString($"marking-{_markingPrototype.ID}-{texture.TexturePath.Filename}"),
                _ => throw new InvalidOperationException("SpriteSpecifier not of known type"),
            };

            container.AddChild(new Label { Text = label });
            container.AddChild(selector);

            selector.Color = marking.MarkingColors[i];

            _colorSliders.Add(selector);

            var colorIndex = i;
            selector.OnColorChanged += _ =>
            {
                if (_updatingControls)
                    return;

                _markingsModel.TrySetMarkingColor(_organ, _layer, _markingPrototype.ID, colorIndex, selector.Color);
            };

            var gradientTypeButton = new OptionButton { HorizontalExpand = true };
            foreach (var type in GradientTypes)
            {
                gradientTypeButton.AddItem(Loc.GetString($"markings-gradient-{type}"), (int) type);
            }

            var gradientColorSelector = new ColorSelectorSliders { SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv };
            var gradientColorContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            var settingsContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            gradientColorContainer.AddChild(new Label { Text = Loc.GetString("markings-gradient-color") });
            gradientColorContainer.AddChild(gradientColorSelector);
            var angleSlider = AddGradientSlider(settingsContainer, Loc.GetString("markings-gradient-angle"), 0f, 360f, 90f, "F0");
            var offsetSlider = AddGradientSlider(settingsContainer, Loc.GetString("markings-gradient-offset"), -1f, 1f, 0f, "F2");
            var softnessSlider = AddGradientSlider(settingsContainer, Loc.GetString("markings-gradient-softness"), 0.02f, 1f, 1f, "F2");

            container.AddChild(new Label { Text = Loc.GetString("markings-gradient") });
            container.AddChild(gradientTypeButton);
            container.AddChild(gradientColorContainer);
            container.AddChild(settingsContainer);

            _gradientTypeButtons.Add(gradientTypeButton);
            _gradientColorSliders.Add(gradientColorSelector);
            _gradientAngleSliders.Add(angleSlider);
            _gradientOffsetSliders.Add(offsetSlider);
            _gradientSoftnessSliders.Add(softnessSlider);
            _gradientColorContainers.Add(gradientColorContainer);
            _gradientSettingsContainers.Add(settingsContainer);

            UpdateGradientControls(marking, colorIndex);

            gradientTypeButton.OnItemSelected += args =>
            {
                gradientTypeButton.SelectId(args.Id);
                var type = (MarkingGradientType) args.Id;
                angleSlider.Value = MarkingGradient.DefaultAngle(type);
                SetGradient(colorIndex);
            };
            gradientColorSelector.OnColorChanged += _ => SetGradient(colorIndex);
            angleSlider.OnValueChanged += _ => SetGradient(colorIndex);
            offsetSlider.OnValueChanged += _ => SetGradient(colorIndex);
            softnessSlider.OnValueChanged += _ => SetGradient(colorIndex);
        }
    }

    private static Slider AddGradientSlider(BoxContainer parent, string label, float min, float max, float value, string format)
    {
        var valueLabel = new Label { Text = $"{label}: {value.ToString(format)}" };
        var slider = new Slider
        {
            HorizontalExpand = true,
            MinValue = min,
            MaxValue = max,
            Value = value,
        };

        slider.OnValueChanged += range =>
        {
            valueLabel.Text = $"{label}: {range.Value.ToString(format)}";
        };

        parent.AddChild(valueLabel);
        parent.AddChild(slider);
        return slider;
    }

    private void UpdateGradientControls(Marking marking, int colorIndex)
    {
        if (_gradientTypeButtons is null ||
            _gradientColorSliders is null ||
            _gradientAngleSliders is null ||
            _gradientOffsetSliders is null ||
            _gradientSoftnessSliders is null ||
            _gradientColorContainers is null ||
            _gradientSettingsContainers is null)
            return;

        var gradient = colorIndex < marking.MarkingGradients.Count
            ? marking.MarkingGradients[colorIndex]
            : MarkingGradient.None;

        _gradientTypeButtons[colorIndex].SelectId((int) gradient.Type);
        _gradientColorSliders[colorIndex].Color = gradient.Color;
        _gradientAngleSliders[colorIndex].Value = gradient.Angle;
        _gradientOffsetSliders[colorIndex].Value = gradient.Offset;
        _gradientSoftnessSliders[colorIndex].Value = gradient.Softness;
        SetGradientColorsVisible(colorIndex, gradient.Type != MarkingGradientType.None);
    }

    private void SetGradient(int colorIndex)
    {
        if (_updatingControls ||
            _gradientTypeButtons is null ||
            _gradientColorSliders is null ||
            _gradientAngleSliders is null ||
            _gradientOffsetSliders is null ||
            _gradientSoftnessSliders is null)
            return;

        var type = (MarkingGradientType) _gradientTypeButtons[colorIndex].SelectedId;
        SetGradientColorsVisible(colorIndex, type != MarkingGradientType.None);

        var gradient = new MarkingGradient(
            type,
            _gradientColorSliders[colorIndex].Color,
            _gradientAngleSliders[colorIndex].Value,
            _gradientOffsetSliders[colorIndex].Value,
            _gradientSoftnessSliders[colorIndex].Value);
        _markingsModel.TrySetMarkingGradient(_organ, _layer, _markingPrototype.ID, colorIndex, gradient);
    }

    private void SetGradientColorsVisible(int colorIndex, bool visible)
    {
        if (_gradientColorContainers is null ||
            _gradientSettingsContainers is null)
            return;

        _gradientColorContainers[colorIndex].Visible = visible;
        _gradientSettingsContainers[colorIndex].Visible = visible;
    }

    public bool CheckMatchesSearch(string query)
    {
        return Loc.GetString($"marking-{_markingPrototype.ID}").Contains(query, StringComparison.OrdinalIgnoreCase);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    private void OnPressed(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        Pressed?.Invoke(args, this);
    }

    private void OnUnpressed(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        Unpressed?.Invoke(args, this);
    }
}
