name: "Labels: Approved"
on:
  pull_request_review:
    types: [submitted]
jobs:
  add_label:
    # Change the repository name after you've made sure the team name is correct for your fork!
    if: ${{ (github.repository == 'dead-space-server/space-erida-14') && (github.event.review.state == 'APPROVED') }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Check user permission
      id: checkPerm
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const username = context.actor;

          const res = await github.rest.repos.getCollaboratorPermissionLevel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            username,
          });

          const perm = res.data.permission; // admin | write | read | none
          console.log("Permission:", perm);

          const allowed = (perm === "admin" || perm === "write");

          core.setOutput("allowed", allowed);

    - name: Add label if allowed
      if: ${{ steps.checkPerm.outputs.allowed == 'true' }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "S: Approved"
